version: '3'

services:
  mawaqit:
    container_name : mawaqit
    build: .
    tty: true
    links:
      - db:mysql
    ports:
      - 443:443
    volumes:
      - ./:/var/www/mawaqit
      - ./docker/data/logs/symfony:/var/www/mawaqit/var/logs
      - ./docker/data/logs/nginx:/var/log/nginx

      - ./docker/config/mawaqit.net.conf:/etc/nginx/sites-enabled/mawaqit.net.conf
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/fpm-pool.conf:/etc/php7/php-fpm.d/mawaqit_custom.conf
      - ./docker/config/php.ini:/etc/php7/conf.d/mawaqit_custom.ini
      - ./docker/data/certbot/conf:/etc/letsencrypt
      - ./docker/data/certbot/www:/var/www/certbot

      - ~/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro
    environment:
      APP_ENV: prod

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/data/certbot/conf:/etc/letsencrypt
      - ./docker/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      
  db:
    container_name : db
    image: mysql:5.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/mawaqit/mysql:/var/lib/mysql
      - /var/www/mawaqit/dbBackups:/home/dbBackups
    environment:
      MYSQL_DATABASE: mawaqit
      MYSQL_ROOT_PASSWORD: mawaqit
