version: '3'

services:
  mawaqit:
    build: .
    container_name: mawaqit
    restart: always
    tty: true
    links:
      - db:mysql
    ports:
      - 80:80
    volumes:
      # symfony code
      - ./:/var/www/mawaqit
      # nginx / php
      - ./docker/config/php/php.ini:/etc/php7/conf.d/mawaqit_custom.ini
      - ./docker/config/php/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/mawaqit.localhost.conf:/etc/nginx/sites-enabled/mawaqit.localhost.conf
      - ./docker/config/nginx/logrotate:/etc/logrotate.d/nginx
      - ./docker/data/logs/nginx:/var/log/nginx
      # ssh
      - ~/.ssh:/root/.ssh
      # clock
      - /etc/localtime:/etc/localtime:ro
      # users
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      APP_ENV: dev
    command: >
      sh -c "chown -R mawaqit:mawaqit /var/tmp/nginx;
      php-fpm7 -F & nginx -g 'daemon off;';"

  db:
    container_name: db
    restart: always
    image: mysql:5.6
    expose:
      - 1106
    ports:
      - 1106:3306
    environment:
      MYSQL_DATABASE: mawaqit
      MYSQL_ROOT_PASSWORD: mawaqit