version: '2'

services:
  mawaqit_prod:
    container_name : mawaqit_prod
    build: .
    tty: true
    links:
      - mawaqit_prod_db:mysql
    expose:
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/mawaqit
      - /etc/localtime:/etc/localtime:ro
      - ~/.ssh:/root/.ssh
      - ../docker/config/vhost.prod:/etc/nginx/sites-enabled/vhost
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      APP_ENV: prod

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      
  mawaqit_prod_db:
    container_name : mawaqit_prod_db
    image: mysql:5.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/mawaqit/mysql:/var/lib/mysql
      - /var/www/mawaqit/dbBackups:/home/dbBackups
    environment:
      MYSQL_DATABASE: mawaqit
      MYSQL_ROOT_PASSWORD: mawaqit
