AppBundle\Entity\Mosque:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MosqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
        name:
            type: string
            length: 1024
        associationName:
            type: string
            length: 255
            nullable: true
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                  updatable: false
                  fields:
                    - name
                    - city    
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 1024
            nullable: true
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
        countryFullName:
            type: string
            length: 255
        zipcode:
            type: string
            length: 255
        latitude:
            type: float
        longitude:
            type: float
        rib:
            type: string
            length: 1024
            nullable: true
        site:
            type: string
            length: 255
            nullable: true
        status:
            type: string
        addOnMap:
            type: boolean
        justificatory:
            type: string
            length: 255
            nullable: true
        image1:
            type: string
            length: 255
            nullable: true
        image2:
            type: string
            length: 255
            nullable: true
        image3:
            type: string
            length: 255
            nullable: true
        locale:
            type: string
            length: 10
            nullable: true
        womenSpace:
            type: boolean
            nullable: true
        janazaPrayer:
            type: boolean
            nullable: true
        aidPrayer:
            type: boolean
            nullable: true
        childrenCourses:
            type: boolean
            nullable: true
        adultCourses:
            type: boolean
            nullable: true
        ramadanMeal:
            type: boolean
            nullable: true
        handicapAccessibility:
            type: boolean
            nullable: true
        ablutions:
            type: boolean
            nullable: true
        parking:
            type: boolean
            nullable: true
        synchronized:
            type: boolean
            nullable: true
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create            
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: mosques
            joinColumn:
                onDelete: CASCADE
    oneToOne:
        configuration:
            targetEntity: AppBundle\Entity\Configuration
            orphanRemoval: true
            cascade:
                - persist
            joinColumn:
                onDelete: CASCADE
        flashMessage:
            targetEntity: AppBundle\Entity\FlashMessage
            orphanRemoval: true
            cascade:
                - persist
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        messages:
            cascade:
                - persist
            targetEntity: AppBundle\Entity\Message
            mappedBy: mosque
            joinColumn:
                onDelete: CASCADE